Feat/mix 4641
Mixgenius/essentia pull request #6
Opened 2016-11-17 21:06 UTC by bscherrer

Added output of detection function to the SBic algorithm.

2016-11-17 22:03 UTC, stuartmansbridge commented on src/algorithms/highlevel/sbic.cpp
> +                bicValues.push_back(tmpBicValues[j]);
How large are these arrays typically? Memory could be allocated to avoid excessive push_back overhead

2016-11-17 22:04 UTC, stuartmansbridge commented on src/algorithms/highlevel/sbic.cpp
> +                bicValues.push_back(tmpBicValues[j+currSeg]);
Same comment as above

2016-11-17 22:07 UTC, bscherrer commented
This page gives an idea of why I did this modification: https://mixgenius.atlassian.net/wiki/display/MER/SBic%3A+an+overview

2016-11-17 22:08 UTC, stuartmansbridge approved these changes
Looks good. One general comment - considering you've taken the trouble to understand the algorithm in detail, there's a few places where comments could be improved or variable names made more descriptive - if you have the energy!

2016-11-17 22:08 UTC, jerome-mixgenius requested changes

2016-11-17 22:08 UTC, jerome-mixgenius commented on src/algorithms/highlevel/sbic.cpp
> +        if (i)
The assignment that was done to i inside the if is gone.

2016-11-17 22:08 UTC, jerome-mixgenius commented on src/algorithms/highlevel/sbic.cpp
> +        if (i)
The assignment that was done to i inside the if is gone.

2016-11-18 15:11 UTC, bscherrer commented on src/algorithms/highlevel/sbic.cpp
> +        if (i)
well, I assign the value to i a few lines above:  i = bicChangeResult.first

2016-11-18 17:10 UTC, bscherrer commented on src/algorithms/highlevel/sbic.cpp
> +        if (i)
Yes, good catch. Thanks

2016-11-22 03:51 UTC, bscherrer commented
I think I have addressed all your concerns. Would you mind having a second look ? Thanks

2016-11-22 12:27 UTC, jerome-mixgenius approved these changes

2016-11-22 14:40 UTC, merged